dprint/dprint-plugin-typescript

src/configuration/types.rs
tests/specs/declarations/enum/EnumDeclaration_MemberSpacing_Blankline.txt
tests/specs/declarations/enum/EnumDeclaration_MemberSpacing_Newline.txt

dprint uses camelcase for its configuration options. This change modifies the enumDeclaration.memberSpacing options to conform to this standard.

fix(config): change enumDeclaration.memberSpacing options to camelCase

---

Cargo.toml

Upgrades swc related crates to latest versions and unpins them.
Closes https://github.com/dprint/dprint-plugin-typescript/issues/78

upgrade: swc_ecmascript, swc_common

---

src/parsing/parser.rs
tests/specs/declarations/class/method/ClassMethod_All.txt
tests/specs/declarations/class/private_method/PrivateMethod_All.txt

The `?` symbols in optional class methods were being doubled for the same reason as in 1a9e904ccfd6237b04ee7ae01b3e1d7df27eeae7. This fixes that.

fix: Don't add second ? to optional methods

---

Cargo.toml
src/parsing/node_helpers.rs
src/parsing/parser.rs
src/utils/string_utils.rs
tests/readme.md
tests/specs/jsx/JsxElement/JsxElement_All.txt
tests/specs/jsx/JsxElement/JsxElement_PreferSingleLine_True.txt
tests/specs/jsx/JsxElement/JsxElement_Spaces.txt
tests/specs/jsx/JsxOpeningElement/JsxOpeningElement_PreferSingleLine_True.txt

A "JSX Space Expression" is a JSXExpressionContainer with a string literal that contains only spaces (ex. `{" "}`, `{"    "}`). This PR adds support for these and treats them as a special kind of separator and combines them for correct compilation output. Previously, dprint-plugin-typescript has not been properly maintaining spaces.
Most importantly, this change fixes the following to properly format:
```ts
function test() {
return <div>{testttttttttttttttttttttttttttttttttttttttttt} {otherrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}</div>;
}
// correctly formats as
function test() {
return <div>
{testttttttttttttttttttttttttttttttttttttttttt}{" "}
{otherrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr}
</div>;
}
```
Additionally, it collapses these away when they are …

Add concept of "JSX Space Expressions"

---

src/parsing/parser.rs
tests/specs/expressions/ArrayExpression/ArrayExpression_Comments.txt
tests/specs/issues/issue0103.txt

Introduces concept of NodeOrSeparator for parse_separated_values.
Todo:
Closes #103

fix: fmt is deleting comment trivia in certain scenarios

---

Cargo.toml
src/parsing/node_helpers.rs
src/parsing/parser.rs
src/parsing/swc/flatten_member_like_expr.rs
src/parsing/swc/mod.rs

This actually makes it simpler.
Todo:
Closes #105

Flatten member-like expressions before parsing to dprint-core IR

---

src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/parsing/parser.rs
tests/specs/expressions/ObjectExpression/ObjectExpression_SpaceSurroundingProperties_False.txt
tests/specs/patterns/ObjectPattern/ObjectPattern_SpaceSurroundingProperties_False.txt
tests/specs/types/TypeLiteral/TypeLiteral_SpaceSurroundingProperties_False.txt

For parity with Prettier’s [`bracketSpacing`](https://prettier.io/docs/en/options.html#bracket-spacing) option.
```ts
const obj = { key: value }; // objectExpression.spaceSurroundingProperties: true (default)
const obj = {key: value}; // objectExpression.spaceSurroundingProperties: false
const { key: value } = obj; // objectPattern.spaceSurroundingProperties: true (default)
const {key: value} = obj; // objectPattern.spaceSurroundingProperties: false
let value: { key: Type }; // typeLiteral.spaceSurroundingProperties: true (default)
let value: {key: Type}; // typeLiteral.spaceSurroundingProperties: false
```
Three separate options may be overkill, but that seems to be consistent with how the other options work.

Add options objectExpression.spaceSurroundingProperties et al.

---

src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
tests/specs/general/SpaceSurroundingProperties_False.txt

This controls the default values of `objectExpression.spaceSurroundingProperties`, `objectPattern.spaceSurroundingProperties`, and `typeLiteral.spaceSurroundingProperties` (#114).

feat: Add spaceSurroundingProperties option

---

Cargo.toml

~~It's necessary to upgrade `dprint-swc-ecma-ast-view` as well, blocked by https://github.com/dprint/dprint-swc-ecma-ast-view/pull/24~~
now all ready!

chore: Upgrade swc_ecmascript to 0.39.0

---

.github/workflows/ci.yml

Currently, when forking the repository and trying to publish a new version via CI (a github release) the CI run fails due to missing credentials.
This disables publishes for Cargo, NPM and into the dprint/plugins repo when running the CI step on a fork.
The only publish that is untouched is the github release, as each fork would have that available by default.
The other option to make this happen is to embed the existence of the secrets (`CI_REPO_PAT`, `CRATES_TOKEN`, `NPM_TOKEN`) into the `if` condition. I think it is less obvious, but let me know if you prefer that.

chore: do not run external resource-dependent publishes in forks

---

src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/parsing/parser.rs
tests/specs/jsx/JsxElement/JsxElement_SpaceBeforeSelfClosingTagSlash_False.txt
tests/specs/jsx/JsxElement/JsxElement_SpaceBeforeSelfClosingTag_False.txt

This PR adds a new configuration option, `jsxElement.spaceBeforeSelfClosingTag`, that controls whether or not a space is inserted before the end of the self closing tag of a JSX element. 
`true`:
```jsx
<Test />
```
`false`:
```jsx
<Test/>
```

jsx: add spaceBeforeSelfClosingTagSlash config

---

src/format_text.rs

tiny one -- `(trace)` wasn't working due to a missing property in `SourceFileInfo`

fix: add missing is_jsx property in trace printing

---

src/parsing/parser.rs
tests/specs/literals/StringLiteral/StringLiteral_QuoteStyle_AlwaysSingle_Jsx.txt

The quote characters for jsx line breaks were hard coded to use double quotes. This PR uses the configured QuoteStyle to create the empty string.
Fixes #300

Fix issue where jsx line breaks were not respecting quote config.

---

src/parsing/parser.rs
tests/specs/general/Jsx_TrailingCommas.txt
tests/specs/issues/issue0303.txt

This changes the JSX type parameter trailing comma logic to only allow a trailing comma if there is only one type parameter which is an identifier. The ambiguity only exists in this specific scenario.
This fixes a bug where a function expression with a generic constraint with type arguments would cause a trailing comma to be added.
This also fixes the test for #303 which ironically also included this ambiguity. swc manages to parse it (without fixing the input) but tsc and VSCode do not, so I have erred on the side adding the comma to the inputs too.

fix: allow JSX generic trailing comma iff required

---

src/parsing/parser.rs
tests/specs/issues/issue0310.txt

Resolves https://github.com/dprint/dprint-plugin-typescript/issues/310.

fix: prevent jsx children wrapping in newlines when not necessary

---

dprint
src/parsing/parser.rs
tests/specs/expressions/ArrayExpression/ArrayExpression_PreferSingleLine_True.txt

Adds a missing check for multiline comments to the `force_use_new_lines` for array expressions when using `preferSingleLine. It's in all of the other list-like expressions, so I guess it was just missed here.
Input:
```
const a = [
["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"], //
];
```
Expected:
```
const a = [
["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"], //
];
```
Output:
```
const a = [["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"], //
["123456", "123456"] //
];
```
Playground link: [here](https://dprint.dev/playground/#code/MYewdgzgLgBAhjAvDA2gKBp1AiAjAJgGYAWAVgDZsAaGPIsygXRoHoWMsU6SLraCeTVuyw4BDPtwnMYbDpi7jeNKbxlzGAbjRA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgBYA …

array expr: add missing comment check for multiline

---

src/generation/generate.rs
tests/specs/general/Arguments_SpaceAround_True.txt

The new `spaceAround` option ([added by](https://github.com/dprint/dprint-plugin-typescript/pull/341) @casieber) is excellent, but it is adding unnecessary spaces when functions don't have arguments:
```js
const a = testing()
if (testing() === true) {
// ...
};
// Generates
const a = testing(  );
if ( testing(  ) === true ) {
// ...
};
// Instead of
const a = testing();
if ( testing() === true ) {
// ...
};
```
_[Playground](https://dprint.dev/playground/#code/MYewdgzgLgBAhjAvDKBTaBLMBzAFASgCgMAzGXNTHApRZKAJwFdV8YBvQmbmAel5gA6YYQC+AbiA/config/N4KABGBEA2CWB2BTA6rAJgFwBaQFxgA4AGAGnCgTUXg1Ux3wBYyJIBXAZ0QBUBDAIw54wAM17QuLKFwC2sAMIB7aIvhD8kAA4AnRCMTbIUyAEc2ijIgDKGAJ7REwyOIDuvWxwAiitvwdHyU3NLAAVtRU11KB1ELm0AN0djJBcAGQREAGlKJ2gRANZORAAhbV4AY1inFyxqADkLKwQAcwd0pAKofjLKkMUOWAxYVScOXhlEdsQAVXgHDg4AC …

fix: do not add spaces with zero arguments

---

src/generation/generate.rs
tests/specs/declarations/import/ImportDeclaration_All.txt
tests/specs/file/sorting/Statements_SortImportDeclarations_CaseInsensitive.txt
tests/specs/file/sorting/Statements_SortImportDeclarations_CaseSensitive.txt
tests/specs/file/sorting/Statements_SortImportDeclarations_Maintain.txt
tests/specs/file/sorting/Statements_SortOrder.txt

fix: don't sort import declarations that only import for side effects

---

Cargo.lock
Cargo.toml
src/generation/generate.rs
tests/specs/declarations/export/ExportDeclaration_ForceSingleLine_True.txt
tests/specs/declarations/import/ImportDeclaration_ForceSingleLine_True.txt

Amendment to #376.
I need to bump the dprint-core version though.

fix: better forcing single line for import and export declarations

---

src/generation/generate.rs
tests/specs/issues/issue0402.txt

fix: maintain param parens in arrow function expr when there's an inner comment

---

src/generation/generate.rs
tests/specs/issues/issue0406.txt

This is a bit of a hack because I'd rather have the case generate its leading comments that it "owns", but doing so would mean the case comment ownership rules would be spread around in multiple places so this is a lot easier.
Closes #406

fix: comments on line above case should not get extra newline when has preceding blank line

---

src/generation/generate.rs
tests/specs/issues/issue0409.txt

fix: maintain indented trailing comments in non-last switch case

---

deployment/schema.json
src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/generation/generate.rs
tests/specs/expressions/ConditionalExpression/ConditionalExpression_LinePerExpression_False.txt
tests/specs/expressions/ConditionalExpression/ConditionalExpression_OperatorPosition_NextLine.txt
tests/specs/expressions/ConditionalExpression/ConditionalExpression_OperatorPosition_SameLine.txt
tests/specs/issues/issue0403.txt

Adds a new `conditionalExpression.linePerExpression` configuration option that defaults to `true` (the current default).
Also features much better comment ownership rules (essentially the colon and question tokens do not own comments, which allows for them to move around without affecting comments in a better way)
Todo:
Closes #403

feat: conditionalExpression.linePerExpression

---

src/generation/generate.rs
tests/specs/issues/issue0421.txt

fix: don't create syntax error with numeric literal as object in member expression

---

deployment/schema.json
src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/generation/generate.rs
tests/specs/jsx/JsxElement/JsxOpeningElement_BracketPosition_Maintain.txt
tests/specs/jsx/JsxElement/JsxOpeningElement_BracketPosition_NextLine.txt
tests/specs/jsx/JsxElement/JsxOpeningElement_BracketPosition_SameLine.txt
tests/specs/jsx/JsxElement/JsxSelfClosingElement_BracketPosition_Maintain.txt
tests/specs/jsx/JsxElement/JsxSelfClosingElement_BracketPosition_NextLine.txt
tests/specs/jsx/JsxElement/JsxSelfClosingElement_BracketPosition_SameLine.txt
tests/specs/jsx/JsxElement/JsxSelfClosingElement_SpaceBeforeSlash_False.txt

Adds:
* `jsxSelfClosingElement.bracketSpacing`
* `jsxOpeningElement.bracketSpacing`
As discussed in #445
Renames `jsx.spaceBeforeSelfClosingTagSlash` -> `jsxSelfClosingElement.spaceBeforeSlash` for consistency.

feat: make `jsx.bracketSpacing` high level config

---

Cargo.lock
Cargo.toml
src/generation/generate.rs
tests/specs/general/Parameters_All.txt
tests/specs/issues/issue0440.txt

fix: correct formatting comment after tailing comma on single line with `"trailingCommas": "always"`

---

.vscode/launch.json

This PR adds a launch.json config to allow debugging via the CodeLLDB extension, which is how I do it on my Macbook. 
It might work on Windows as well, could you try? If so, then we can probably just delete the other launch configuration.

debugging: add launch.json configuration for CodeLLDB-based debugging

---

src/generation/generate.rs
tests/specs/comments/CommentBlocks_All.txt

Block comments like this:
```
/*
* hello
* world!
*/
```
should get the same leading whitespace / indentation treatment as JSDoc. This PR aligns that and tweaks the JSDoc code to allow it, instead of using the super-basic `js_like_comment_block` in dprint core. I did start out fixing `js_like_comment_block` first, but that change got far too involved (especially for `core`, which is language agnostic), and this change was much shorter and also gives us future parity with any similar JSDoc improvements.
This aligns with Prettier: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSgAj+nAWwE8cBDQsgLwEsoBzHSQwhGbPHdVbSKAZxg4AZhAg4AvDgCMAbmzYMWXPiKkK1Oo2atYHfDyh9BIsZJmyQAGhAQADjBrR+yUGQBO7iAHcACh4QXFDIAG28yYhcbACN3MjAAazgYAGUKOAAZOjhkYVD+OBi4xOSUu3itZBh3AFdCkDhCaLgAExbWjLIGGrJ6OAAxCHdKGEc …

comments: trim excessive whitespace at the start of multi-line block comments

---

src/generation/generate.rs
tests/specs/expressions/ParenExpr/ParenExpr_All.txt

Input:
```ts
const a = (((1)));
```
Expected:
```ts
const a = 1;
```
Actual:
```ts
const a = (1);
```
Seems like this was perhaps meant to be handled by the `AssignExpr` immediately above where I made my change, but I debugged it and it seems to be a `VarDeclarator` instead.

fix: unwrap outer parens if it's the RHS of a var declaration

---

src/generation/generate.rs
tests/specs/issues/issue0468.txt

fix: braces in blocks with conditional braces should not be removed when containing a single empty statement

---

src/generation/generate.rs
tests/specs/issues/issue0510.txt

fix: keep braces on if & while statements when block body contains single decl

---

Cargo.lock
Cargo.toml
src/swc.rs
tests/specs/expressions/ArrowFunctionExpression/ArrowFunctionExpression_All.txt
tests/specs/expressions/FunctionExpression/FunctionExpression_All.txt

fix: swc upgrade - ensure const type params not removed in arrow functions

---

src/generation/generate.rs
tests/specs/issues/issue0533.txt

fix: arrow func single param paren should not be removed when has trailing comma with trailing comments

---

src/generation/generate.rs
tests/specs/issues/deno/issue020089.txt

For https://github.com/denoland/deno/issues/20089

fix(asi): do not put semi-colon at start of expression stmt body in do while stmt

---

src/generation/context.rs
tests/specs/literals/StringLiteral/StringLiteral_QuoteProps_Consistent.txt

Caused by mindlessly accepting a copilot suggestion. You can see the correct code becoming incorrect in this commit:
https://github.com/dprint/dprint-plugin-typescript/pull/544/commits/3df111e5a8bafdd9a45d1818d51ebf263a64a6d5

fix: quote props consistent

---

Cargo.lock
Cargo.toml
src/generation/generate.rs
tests/specs/declarations/export/ExportAllDeclaration_All.txt
tests/specs/declarations/export/ExportNamedDeclaration_All.txt
tests/specs/declarations/import/ImportDeclaration_All.txt

This adds support for import attributes, while maintaining import assertions for now.
In the future, this will probably automatically convert import assertions to import attributes.

feat: support import attributes

---

src/generation/generate.rs
tests/specs/issues/issue0556.txt

fix(regression): call expr with/without optional chain should not format differently in tpl lit

---

src/generation/generate.rs
tests/specs/expressions/BinaryExpression/BinaryExpression_Unary_In.txt

At a [TC39 meeting this week](https://github.com/tc39/agendas/blob/main/2023/09.md) we are discuss about a proposal for `!in` and `!instanceof`, to allow writing `x !in y` rather than `!(x in y)`. One of the main motivator factors is that it's very common ([see the slides that will be presented](https://docs.google.com/presentation/d/1vwNOjUiUvy6TzK6t0Mb8qgyKwBNszly9HibJJpUa_Eo/edit#slide=id.g27f462e9ca3_0_0)) to forget parentheses around `(x in y)` when writing `!(x in y)`.
Given the easy confusion, formatters could add parenthesis to make meaning of the code clear. If my code is automatically formatted to `(!x) in y`, if would not assume that it's doing `!(x in y)`. (**NOTE** This is my idea, not TC39's position -- we didn't actually talk about that proposal yet :) ) How do you feel …

feat: add parens around unary expressions in in/instanceof

---

src/generation/generate.rs
tests/specs/issues/deno/issue021279.txt

For https://github.com/denoland/deno/issues/21279

fix: maintain parens for jsx element in member expr

---

src/generation/generate.rs
tests/specs/general/Arguments_SpaceAround_True.txt

Fixes #581
The `if !force_use_new_lines && nodes.len() == 1 && is_arrow_function_with_expr_body(nodes[0])` path wasn't considering the `space_around` option. I'm not sure if this is the most correct way to fix this problem, but it at least works on my codebase and passes the tests.

fix: `arguments.spaceAround` not adding spaces when an arrow function is the only argument

---

deployment/schema.json
src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/generation/generate.rs
tests/specs/clauses/catchClause/CatchClause_SpaceAround_True.txt

This adds spaces around the parameter in a catch clause. Examples:
```ts
// catchClause.spaceAround: false
try {
a;
}
catch(ex){
b;
}
// catchClause.spaceAround: true
try {
a;
} catch ( ex ) {
b;
}
```

feat: add catchClause.spaceAround

---

deployment/schema.json
src/configuration/types.rs
src/generation/generate.rs
tests/specs/declarations/export/ExportDeclaration_ForceMultiLine_OnlyWhenMultiple.txt
tests/specs/declarations/import/ImportDeclaration_ForceMultiLine_OnlyWhenMultiple.txt

Just thought of this. It's slightly shorter.
Follow up to #617

refactor: rename `onlyWhenMultiple` to `whenMultiple`

---

Cargo.lock
Cargo.toml

dprint isn't affected by this, but need to downgrade swc for Deno due to https://github.com/swc-project/swc/issues/8840

fix: deno_ast 0.36

---

src/generation/generate.rs
tests/specs/declarations/function/Function_SpaceBeforeParentheses_True.txt
tests/specs/expressions/FunctionExpression/FunctionExpression_SpaceBeforeParentheses_True.txt

Closes https://github.com/dprint/dprint-plugin-typescript/issues/642

fix: correct spaceBeforeParentheses for `export default function` with name

---

Cargo.lock
Cargo.toml
src/generation/generate.rs
tests/specs/issues/issue0650.txt

Closes https://github.com/dprint/dprint-plugin-typescript/issues/650

fix: trailing comments sometimes being inserted before the comma in parameter lists

---

deployment/schema.json
src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/generation/generate.rs
src/generation/sorting/mod.rs
tests/specs/declarations/export/NamedExports_SortNamedTypeExports_First.txt
tests/specs/declarations/export/NamedExports_SortNamedTypeExports_Last.txt
tests/specs/declarations/export/NamedExports_SortNamedTypeExports_None.txt
tests/specs/declarations/export/NamedExports_SortOrder_CaseInsensitive.txt
tests/specs/declarations/import/NamedImports_SortNamedTypeImports_First.txt
tests/specs/declarations/import/NamedImports_SortNamedTypeImports_Last.txt
tests/specs/declarations/import/NamedImports_SortNamedTypeImports_None.txt
tests/specs/declarations/import/NamedImports_SortOrder_CaseInsensitive.txt

Two new options:
* `importDeclaration.sortTypeOnlyImports`
* `exportDeclaration.sortTypeOnlyExports`
With possible values:
* `first` - Sorts type only named imports/exports first
* `last` (default) - Sorts type only named imports/exports last
* `none` - Does not sort based on if a type only named import or export
For https://github.com/denoland/deno/issues/22583

feat: ability to sort type only named imports and exports first or last

---

deployment/schema.json
src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
tests/specs/declarations/export/NamedExports_SortOrder_CaseInsensitive.txt
tests/specs/declarations/import/NamedImports_SortOrder_CaseInsensitive.txt

I think this should be off by default to the chance of merge conflicts. People rarely look at named imports/exports.

fix: revert back default type only named imports/exports sorting to "none"

---

src/configuration/builder.rs
src/configuration/resolve_config.rs
src/configuration/types.rs
src/generation/generate.rs
tests/specs/file_indent_level/FileIndentLevel.txt

This is for plugins like https://github.com/g-plane/markup_fmt when they need to format at a specific indentation level for stuff like `<script>` tags.
Todo: investigate naming

feat: ability to format a file at a specific indentation level

---

Cargo.lock
Cargo.toml

This is to ensure the tests still pass with the deno_ast upgrade.

chore: deno_ast 0.46.3

---

src/generation/generate.rs

Fixes #709
Also, wasn't able to create a spec for this change, as the current testing is not flexible enough to add custom configurations on a per case basis. It also seems like since the spec parsing is part of `dprint_core`, I'm assuming that change might be massive.

fix: external formatter should be able to handle tab characters

---

src/format_text.rs
src/generation/context.rs
src/generation/generate.rs
tests/spec_test.rs

related https://github.com/denoland/deno/issues/29217

feat: allow external formatter to cause formatting error

---

Cargo.toml
src/format_text.rs
src/generation/generate.rs
tests/spec_test.rs
tests/specs/external_formatter/css.txt

We currently use the pattern `dpr1nt_00_d` (number part incremented by occurrence) for placeholder for expression occurrence in template literals. This causes a problem when the expression used as key-value pair (or block) replacement in embedded CSS template literals. This happens because `dpr1nt_00_d` only works as key or value of property in CSS, and it doesn't work as key-value pair replacement.
This PR tries to fix it by using the pattern `@dpr1nt_00_d` in CSS template literals, and changing the css syntax to LESS. In LESS `@var` can be both values and mixins (mixin works as replacement of key-value pair).
Note: prettier uses `@prettier-placeholder-0-id` for placeholder. ref https://github.com/prettier/prettier/blob/d75b21f4b6e86f5751738f51083d685bb4a97965/src/language-js/embed/css.js …

fix: allow expression to be used as key-value pair or block in embedded css

---

src/format_text.rs
src/generation/generate.rs

This fixes the line number in error message when external formatter raised syntax error
related: https://github.com/denoland/deno/issues/29660#issuecomment-2954240031

fix: line number in syntax error message from external formatter

---

src/generation/generate.rs
tests/specs/external_formatter/html.txt

This PR fixes the handling of indent inside the template literals with embedded languages.
Currently the leading whitespaces in the line of embedded external languages are handled as part of source code, and that causes the issue https://github.com/denoland/deno/issues/29164 . This PR fixes it by skipping the leading whitespaces, but instead adding `StartIndent` and `FinishIndent` IR signals based on current indent level of the embedded language.
related https://github.com/denoland/deno/issues/29164

fix: handling of indent inside embedded language

---

src/format_text.rs
src/generation/context.rs
src/generation/generate.rs
tests/spec_test.rs

Working on https://github.com/denoland/deno/pull/29851#discussion_r2162069234
I realized it's not possible to support any tagged template without first
updating `dprint-plugin-typescript` and possibly `deno_media_type`.

refactor(BREAKING): external formatter accepts string instead of MediaType

---

src/generation/generate.rs
tests/specs/issues/deno/issue030443.txt

* https://github.com/denoland/deno/issues/30443

fix: keep paren around expr for `@satisfies` jsdoc
