- Cargo.lock
- Cargo.toml
> upgrade swc_ecma_ast 0.26.0, swc_ecma_parser 0.31.0

- Cargo.toml
Updating the swc dependencies to the latest release.
> chore: update swc dependencies

- Cargo.toml
- upgrade swc_ecmascript to 0.17.0
- upgrade swc_common to 0.10.8
> chore(release): 0.38.0

- src/parsing/parser.rs
- tests/specs/expressions/ObjectExpression/ObjectExpression_All.txt
> Inline as multi-line object literals in arguments

- src/parsing/parser.rs
- tests/specs/issues/issue0046.txt
- tests/specs/statements/ifStatement/IfStatement_UseBraces_WhenNotSingleLine.txt
> Single line if statement going to multiple lines should keep the header on one line if able

- src/parsing/parser.rs
- tests/specs/literals/TemplateLiteral/TemplateLiteral_All.txt
Closes #117.
If you are not going to squash it, please tell me so I can squash it :)
> Fix placement of template literals in arrow bodies

- Cargo.toml
Depends on https://github.com/dprint/dprint-swc-ecma-ast-view/pull/26﻿
> update swc + 0.47.0

- tests/specs/file/sorting/Statements_SortImportDeclarations_Alpha.txt
for https://github.com/dprint/dprint-plugin-typescript/issues/270#issuecomment-908222906
> tests: add test case for alphabetical order with relative paths

- src/parsing/parser.rs
- tests/specs/comments/JSDocComments_All.txt
- tests/specs/issues/issue0141.txt
Will merge this tomorrow.
Closes #141
> feat: basic JS doc formatting

- src/configuration/builder.rs
- src/configuration/resolve_config.rs
- src/configuration/types.rs
- src/parsing/parser.rs
- tests/specs/issues/issue0094.txt
- tests/specs/issues/old-repo/issue131.txt
- tests/specs/jsx/JsxElement/JsxElement_MultiLineParens_Always.txt
- tests/specs/jsx/JsxElement/JsxElement_MultiLineParens_Never.txt
- tests/specs/jsx/JsxElement/JsxElement_MultiLineParens_Prefer.txt
- tests/specs/jsx/JsxExpressionContainer/JsxExpressionContainer_All.txt
- tests/specs/jsx/JsxFragment/JsxFragment_MultiLineParens_False.txt
- tests/specs/jsx/JsxText/JsxText_All.txt
Resolves https://github.com/dprint/dprint-plugin-typescript/issues/301.
> jsx: add multiLineParens=always

- src/utils/char_iterator.rs
- src/utils/file_text_has_ignore_comment.rs
This change replaces the `CharIterator` struct with the `IteratorCharExt` trait that is implemented for `Peekable<Chars>`. This has the benefits that
- we don't have to wrap `Chars` as `CharIterator`, and subsequently implement iterator peeking ourselves. Instead we can rely on the `Peekable` struct provided in `std::iter`; and
- we are able to extend the functionality of `Peekable<Chars>` (and any other types that implement `IteratorCharExt`).
I hope this change accurately actions the todo. Happy to work through additional improvements or ways we can make this more flexible if there are areas that would benefit from its reuse.
> Replace CharIterator struct with IteratorCharExt trait

- .github/workflows/ci.yml
- Cargo.toml
> feat: upgrade to deno_ast 0.7

- src/configuration/resolve_config.rs
- tests/specs/expressions/TaggedTemplateExpression/TaggedTemplateExpression_All.txt
- tests/specs/literals/TemplateLiteral/TemplateLiteral_All.txt
> Flip the default value of taggedTemplate.spaceBeforeLiteral

- Cargo.lock
- Cargo.toml
- src/format_text.rs
- src/generation/generate.rs
- src/swc.rs
- tests/specs/types/TypeParameter/TypeParameter_All.txt
Will be coming up in a TypeScript release.
> feat: support TypeScript's optional variance annotations

- src/format_text.rs
- src/swc.rs
- tests/specs/issues/issue0373.txt
> fix: do not surface parse error parsing certain jsx in .js files

- deployment/schema.json
- src/configuration/builder.rs
- src/configuration/resolve_config.rs
- src/configuration/types.rs
- src/generation/generate.rs
- src/generation/swc/helpers.rs
- src/generation/swc/mod.rs
- tests/specs/declarations/export/ExportDeclaration_ForceSingleLine_True.txt
- tests/specs/declarations/import/ImportDeclaration_ForceSingleLine_True.txt
> feat: add `importDeclaration.forceSingleLine` and `exportDeclaration.forceSingleLine`

- README.md
This would have saved me 20 mins :)
Cheers.
> chore: add build instructions in readme

- src/generation/generate.rs
- src/generation/swc/flatten_curried_arrows.rs
- src/generation/swc/mod.rs
- tests/specs/expressions/ArrowFunctionExpression/ArrowFunctionExpression_All.txt
- tests/specs/expressions/BinaryExpression/BinaryExpression_All.txt
> fix: support curried arrow functions

- src/generation/generate.rs
- tests/specs/issues/issue0359.txt
Fixes #359.
I'm a noob in this codebase, let me know if I've missed something obvious!
> Ensure if body stays on same line when condition is multiline

- deployment/schema.json
- src/configuration/builder.rs
- src/configuration/resolve_config.rs
- src/configuration/types.rs
- src/generation/generate.rs
- tests/specs/expressions/ConditionalExpression/ConditionalExpression_All.txt
- tests/specs/expressions/ConditionalExpression/ConditionalExpression_OperatorPosition_Maintain.txt
- tests/specs/issues/issue0413.txt
- tests/specs/types/ConditionalType/ConditionalType_All.txt
- tests/specs/types/ConditionalType/ConditionalType_OperatorPosition_Maintain.txt
- tests/specs/types/ConditionalType/ConditionalType_OperatorPosition_NextLine.txt
- tests/specs/types/ConditionalType/ConditionalType_OperatorPosition_SameLine.txt
> feat: conditionalExpression.operatorPosition

- src/generation/generate.rs
- tests/specs/issues/issue0415.txt
> fix: semi-colon for index signatures in class declarations

- src/generation/generate.rs
- tests/specs/issues/issue0416.txt
> fix: useBraces: whenNotSingleLine should not add braces when header end ln == statement end ln

- src/generation/generate.rs
- tests/specs/issues/issue0426.txt
Fixes #426
Turns out this was more trivial than I expected it would be
> fix: emit TypeQuery type arguments

- src/generation/generate.rs
- tests/specs/expressions/ConditionalExpression/ConditionalExpression_OperatorPosition_Maintain.txt
- tests/specs/issues/issue0424.txt
> feat: operatorPosition: maintain should be per token

- deployment/schema.json
- src/configuration/builder.rs
- src/configuration/resolve_config.rs
- src/configuration/types.rs
- src/generation/generate.rs
- tests/specs/statements/doWhileStatement/DoWhileStatement_NextControlFlowPosition_Maintain.txt
- tests/specs/statements/doWhileStatement/DoWhileStatement_NextControlFlowPosition_NextLine.txt
- tests/specs/statements/doWhileStatement/DoWhileStatement_NextControlFlowPosition_SameLine.txt
> feat: add `doWhileStatement.nextControlFlowPosition`

- deployment/schema.json
- src/configuration/builder.rs
- src/configuration/resolve_config.rs
- src/configuration/types.rs
- src/generation/generate.rs
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_Maintain.txt
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_NextLine.txt
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_SameLine.txt
> feat: add `jsx.bracketPosition`

- src/generation/generate.rs
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_Maintain.txt
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_NextLine.txt
- tests/specs/jsx/JsxElement/JsxElement_BracketPosition_SameLine.txt
Will add the split up config in a separate pr.
Closes #445
> fix: jsx.bracketPosition - Was adding an extra space when single line

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/generation/context.rs
- src/generation/generate.rs
- src/lib.rs
- src/swc.rs
- tests/specs/types/TypeParameter/TypeParameter_All.txt
- tests/test.rs
> feat: support const type parameters

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Cargo.lock
- Cargo.toml
- src/generation/generate.rs
- src/swc.rs
- tests/specs/declarations/class/auto_accessor/AutoAccessor_All.txt
- tests/specs/declarations/class/decorator/Decorator_All.txt
- tests/specs/declarations/export/ExportAllDeclaration_All.txt
- tests/test.rs
Waiting on swc to support ES decorators though.
> feat: upgrade for TypeScript 5.0 (except decorators)

- src/generation/generate.rs
- src/utils/string_utils.rs
- tests/specs/issues/issue0511.txt
> fix: ensure stable formatting for comment with spaced asterisks

- src/generation/generate.rs
- tests/specs/issues/issue0520.txt
> perf: improve speed of minified object literals

- src/generation/generate.rs
- tests/specs/issues/issue0516.txt
> fix: ensure no trailing space after colon token in conditional type

- src/generation/generate.rs
- tests/specs/issues/issue0565.txt
> fix: multi-line string indent was broken in some cases

- src/generation/generate.rs
- tests/specs/declarations/class/auto_accessor/AutoAccessor_All.txt
> fix: AutoAccessor was losing non-null assertion

- src/swc.rs
> fix: error on merge conflict marker

- Cargo.lock
- Cargo.toml
- src/generation/generate.rs
- src/generation/node_helpers.rs
- src/swc.rs
- tests/specs/declarations/import/ImportDeclaration_All.txt
- tests/specs/expressions/CallExpression/CallExpression_All.txt
Waiting on a deno_ast release.
> feat: support source phase imports

- Cargo.lock
- Cargo.toml
- src/generation/generate.rs
- src/wasm_plugin.rs
Fixes a memory leak and improves performance.
> perf: upgrade dprint-core 0.66

- Cargo.lock
- Cargo.toml
- src/generation/generate.rs
- tests/specs/declarations/class/auto_accessor/AutoAccessor_All.txt
> fix: support abstract auto-accessors

- src/generation/generate.rs
- src/lib.rs
- tests/specs/issues/issue0632.txt
Closes https://github.com/dprint/dprint-plugin-typescript/issues/632
> fix: `else` was moved to wrong `if` sometimes when formatting minified code

- src/format_text.rs
Previously the dprint CLI would maintain the BOM, but that should not have been a concern for it. Now it seems dprint-plugin-typescript has stripped the BOM when formatting a new file, but it should strip the BOM always to be consistent.
> feat: strip BOM on files without any changes otherwise

- Cargo.lock
- Cargo.toml
- rust-toolchain.toml
- src/generation/generate.rs
- src/generation/node_helpers.rs
- src/generation/swc/flatten_member_like_expr.rs
~~Waiting on https://github.com/denoland/deno_ast/pull/263~~
> perf: deno_ast 0.41

- src/generation/generate.rs
- src/utils/is_prefix_semi_colon_insertion_char.rs
- tests/specs/statements/expressionStatement/ExpressionStatement_SemiColonInsertion.txt
fix #24285
#https://github.com/denoland/deno/issues/24285
> fix: prevent prefix semicolon insertion for increment and decrement

- src/generation/generate.rs
- tests/specs/declarations/using/Using_All.txt
For https://github.com/denoland/deno/issues/24406
> fix: support using decl in for of stmt

- src/generation/generate.rs
- tests/specs/issues/deno/issue026681.txt
For https://github.com/denoland/deno/issues/26681
> fix: handle jsx ignore container followed by jsx text
